apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort   # Change to LoadBalancer if using cloud
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007   # Optional (range: 30000-32767)
